version: "3"


x-common: &commons
    deploy:
        resources:
            limits:
                cpus: '0.5'
                memory: 500m

    mem_swappiness: 0
    memswap_limit: 0


services:
    blockproducer:
        build: .
        image: leap:3.1.3
        container_name: blockproducer
        command: ["bash", "/docker/run_leap.sh"]

        volumes:
            - ./docker:/docker:ro

        ports:
            - "8888:8888/tcp"

        healthcheck:
            test: ["CMD", "curl", "http://localhost:8888/v1/chain/get_info"]
            interval: 2s
            timeout: 2s
            retries: 3
            start_period: 60s


    deployer:
        build: .
        image: leap:3.1.3
        container_name: deployer
        command: ["bash", "/docker/deploy.sh"]

        volumes:
            - ./docker:/docker:ro

        depends_on:
            blockproducer:
                condition: service_healthy
